name: .NET

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish 
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: JustWind-${{ github.ref_name }}
        path: bin/Release/net6.0/win-x64/publish/*
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: JustWind-${{ github.ref_name }}
